function NtoR(X1, Y1, TITULO, Yl)
%CREATEFIGURE(X1, Y1)
%  X1:  stem x
%  Y1:  stem y

%  Auto-generated by MATLAB on 12-Apr-2019 01:56:51

% Create figure
figure1 = figure('Name', TITULO);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stem
stem(X1,Y1,'filled');

% Create ylabel
ylabel(Yl);

% Create xlabel
xlabel('n');

% Create title
title(TITULO);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[Xmin-1 Xmax+1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[Ylim-1 Ymax+1]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Consolas');
