function NtoR2(X1,Y1,Z1,TITULO)
%CREATEFIGURE(X1)
%  X1:  stem3 x

%  Auto-generated by MATLAB on 15-Apr-2019 16:25:38

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stem3
stem3(X1,Y1,Z1,'filled');

% Create zlabel
zlabel('Parte Imaginaria');

% Create ylabel
ylabel('Parte Real');

% Create xlabel
xlabel('n');

% Create title
title(TITULO);

view(axes1,[-37.5 30]);
grid(axes1,'on');
