function m2(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data
  t=0:0.001:5;
  
%  Auto-generated by MATLAB on 15-Mar-2019 19:51:54

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1);

